#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Labb02.Resource", IsApplication=true)]

namespace Labb02
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040000
			public const int event_column_label_text_size = 2130968576;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07000a
			public const int btnAddEvent = 2131165194;
			
			// aapt resource value: 0x7f07000f
			public const int btnCreateReports = 2131165199;
			
			// aapt resource value: 0x7f070004
			public const int btnDate = 2131165188;
			
			// aapt resource value: 0x7f07000d
			public const int btnNewEvent = 2131165197;
			
			// aapt resource value: 0x7f070003
			public const int btnSetExpense = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int btnSetIncome = 2131165186;
			
			// aapt resource value: 0x7f07000e
			public const int btnShowAllEvents = 2131165198;
			
			// aapt resource value: 0x7f070005
			public const int etDescription = 2131165189;
			
			// aapt resource value: 0x7f070008
			public const int etTotalSum = 2131165192;
			
			// aapt resource value: 0x7f07000c
			public const int llMenu = 2131165196;
			
			// aapt resource value: 0x7f070000
			public const int rlRoot = 2131165184;
			
			// aapt resource value: 0x7f070007
			public const int spinAccount = 2131165191;
			
			// aapt resource value: 0x7f070006
			public const int spinType = 2131165190;
			
			// aapt resource value: 0x7f070009
			public const int spinVAT = 2131165193;
			
			// aapt resource value: 0x7f070001
			public const int tvDescription = 2131165185;
			
			// aapt resource value: 0x7f07000b
			public const int tvHeader = 2131165195;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f050001
			public const int event_column_data_weight = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int event_column_label_weight = 2131034112;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Event = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060000
			public const int ApplicationName = 2131099648;
			
			// aapt resource value: 0x7f060006
			public const int eventAddEvent = 2131099654;
			
			// aapt resource value: 0x7f060009
			public const int eventDate = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int eventDescription = 2131099658;
			
			// aapt resource value: 0x7f060008
			public const int eventExpense = 2131099656;
			
			// aapt resource value: 0x7f060007
			public const int eventIncome = 2131099655;
			
			// aapt resource value: 0x7f060005
			public const int eventInstructions = 2131099653;
			
			// aapt resource value: 0x7f06000c
			public const int eventToFromAccount = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int eventTotalSumVAT = 2131099661;
			
			// aapt resource value: 0x7f06000b
			public const int eventType = 2131099659;
			
			// aapt resource value: 0x7f06000e
			public const int eventVAT = 2131099662;
			
			// aapt resource value: 0x7f060004
			public const int mainMenuCreateReports = 2131099652;
			
			// aapt resource value: 0x7f060001
			public const int mainMenuHeader = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int mainMenuNewEvent = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int mainMenuShowAllEvents = 2131099651;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
